-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(30*(C.DAILY_FEE-(C.DAILY_FEE*(P.DISCOUNT_RATE/100))),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C 
LEFT JOIN 
(
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= "2022-11-30" AND END_DATE >= "2022-11-01"
    GROUP BY CAR_ID
) AS H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE
WHERE (C.CAR_TYPE = "세단" OR C.CAR_TYPE = "SUV") AND P.DURATION_TYPE = "30일 이상" AND H.CAR_ID IS NULL
GROUP BY C.CAR_ID
HAVING FEE >= 500000 AND FEE <= 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;