-- 코드를 입력하세요
SELECT A.FLAVOR
FROM 
(
SELECT F.FLAVOR AS FLAVOR, SUM(F.TOTAL_ORDER)+SUM(J.TOTAL_ORDER) AS TOTAL
FROM FIRST_HALF AS F JOIN JULY AS J ON F.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
) AS A
ORDER BY A.TOTAL DESC
LIMIT 3;